// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d07374b9-7191-4d99-a5cd-89bfbf924093";

const char SSID[]               = "PTEROPUS";    // Network SSID (name)
const char PASS[]               = "***";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "********";    // Secret device password

void onSwitch1Change();
void onSwitch2Change();

String alert;
CloudSwitch switch1;
CloudSwitch switch2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(alert, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(switch1, READWRITE, ON_CHANGE, onSwitch1Change);
  ArduinoCloud.addProperty(switch2, READWRITE, ON_CHANGE, onSwitch2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
